rofiles-fuse: Build using FUSE 3 if possible, falling back to FUSE 2
ostreedev/ostree pull request #2376
Opened 2021-06-17 23:32 UTC by smcv

2021-06-17 23:59 UTC, dbnicholson commented
/ok-to-test

2021-06-18 16:02 UTC, dbnicholson requested changes
Could you adjust one of the CI environments to use fuse3? I think the following would do it:
```
diff --git a/.travis.yml b/.travis.yml
index 10d8e4bf..7b476af4 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,7 +7,8 @@ env:
   - ci_docker=debian:buster-slim ci_distro=debian ci_suite=buster ci_configopts="--with-curl --with-ed25519-libsodium --without-gpgme" ci_pkgs="libsodium-dev"
   # A 32 bit build to act as a proxy for frequently deployed 32 bit armv7
   - ci_docker=i386/debian:buster-slim ci_distro=debian ci_suite=buster
-  - ci_docker=ubuntu:focal ci_distro=ubuntu ci_suite=focal
+  # Include libfuse3-dev to exercise the fuse3 API usage in rofiles-fuse
+  - ci_docker=ubuntu:focal ci_distro=ubuntu ci_suite=focal ci_pkgs="libfuse3-dev"
   - ci_docker=ubuntu:groovy ci_distro=ubuntu ci_suite=groovy
 
 script:
```
I picked Ubuntu focal, but it could probably be any of those environments.

2021-06-18 16:46 UTC, smcv commented
> Could you adjust one of the CI environments to use fuse3?

Sorry, I don't really understand how libostree's CI works. I don't see a Travis-CI build pass being done on this PR; perhaps the Travis-CI metadata is used in forks like mine, but not here?

2021-06-18 16:50 UTC, smcv commented on src/rofiles-fuse/main.c
> +  if (renameat2 (basefd, from, basefd, to, flags) == -1)
renameat2 was new in 3.15, according to my renameat(2) on Debian unstable.

If someone is still using older Linux versions (Debian 7, Ubuntu 14.04 and contemporary distributions) then I don't think they can expect to also run the latest libostree. The only thing I can think of to make this more portable to ye olde kernels would be:

```
if (flags == 0)
  result = renameat (basefd, from, basefd, to);
else
  result = renameat2 (basefd, from, basefd, to, flags);

if (result == -1)
...
```

Would you prefer that? It's more code and realistically nobody is going to test it.

2021-06-18 17:10 UTC, dbnicholson commented
> Sorry, I don't really understand how libostree's CI works. I don't see a Travis-CI build pass being done on this PR; perhaps the Travis-CI metadata is used in forks like mine, but not here?

That's... strange. Perhaps someone turned it off since it fails so often due to rate limiting. It usually runs on my PRs and that's the way the `make check` test suite is run on the widest variety of distros. Today I'm working on getting GitHub Actions CI going to replace Travis, but in the meantime it would be nice to put the option in so I can convert it even if it's not doing anything at the moment. Or I can add a commit to do it.

2021-06-18 17:13 UTC, dbnicholson commented on src/rofiles-fuse/main.c
> +  if (renameat2 (basefd, from, basefd, to, flags) == -1)
I think it's fine the way you have it without the fallback. Thanks for digging up the details there. In the past there have been several "make this work on RHEL 7" commits. Google tells me it has 3.10, but then RedHat also backports a lot of stuff onto their kernels.

Anyways, I think it's fine and anyone trying to backport to very old distros can always open an issue.

2021-06-18 18:07 UTC, smcv commented
This branch is certainly not urgent to merge, I need to test it on an older and newer distro before landing it anyway.

I'll try to have at least one CI build with fuse3 and at least one without, in whatever state the CI is in when I get to this.

2021-06-18 21:06 UTC, dbnicholson commented
If/when you finish this, could you add a Fixes: #1881 to the commit log?

2021-06-21 16:37 UTC, cgwalters commented on src/rofiles-fuse/main.c
> +  if (renameat2 (basefd, from, basefd, to, flags) == -1)
From my PoV no need to do any further ostree work for RHEL7, in the extremely unlikely case we (RH) are on the hook for that we'll backport things selectively.

2021-06-21 17:15 UTC, cgwalters approved these changes
Thanks for working on this!

I think we can likely consider older fuse deprecated too, maybe a few months after this make it require a `--enable-deprecated-fuse` or so.

2022-01-03 10:36 UTC, lucab commented
I'd be interested in merging this in the near future.
@smcv do you have time to rebase and mark it as non-draft? Or do you want me to take over this for the final polishing steps?

2022-01-03 13:56 UTC, smcv commented
> do you have time to rebase and mark it as non-draft? Or do you want me to take over this for the final polishing steps?

Would you mind taking over? It's going to be a little while before I can concentrate on this again.

2022-01-03 16:17 UTC, lucab commented
@smcv sure, no problem. I'll check tomorrow if I have enough privileges to directly rebase this branch/PR, otherwise I'll open a new one.

2022-01-04 09:44 UTC, lucab commented
I only had to adapt CI configuration, rest of the code was already conflict-free.
I've enabled auto-merging, so it should get in once CI finishes.
Thanks for the PR!

2022-01-04 10:27 UTC, merged