ci: Drop Debian testing
ostreedev/ostree pull request #2699
Opened 2022-08-22 20:00 UTC by cgwalters

I didn't deep dive into debugging this but I'm pretty sure it's
 https://gitlab.gnome.org/GNOME/glib/-/issues/2580
which is us having an older Docker in the middle here.

2022-08-22 20:51 UTC, dbnicholson requested changes
This seems like almost the same issue I saw on one of the Ubuntu builds awhile ago. Could you try running it with `container-options: --security-opt seccomp=unconfined`? See the `ubuntu:rolling` build below.

2022-08-22 21:00 UTC, cgwalters commented
> This seems like almost the same issue I saw on one of the Ubuntu builds awhile ago. Could you try running it with container-options: --security-opt seccomp=unconfined? See the ubuntu:rolling build below.

Likely, thanks!

2022-08-22 21:13 UTC, dbnicholson approved these changes

2022-08-23 07:16 UTC, lucab commented
/retest

2022-08-23 07:35 UTC, lucab commented
It looks like Prow got stuck and it also fails to re-trigger, overriding.

/override ci/prow/sanity

2022-08-23 07:35 UTC, merged