libostree: Ignore new_and_connect in the introspection
ostreedev/ostree pull request #2813
Opened 2023-02-08 09:57 UTC by tintou

This function can't be correctly introspected and it is easy enough to connect to the signal afterwards.

2023-02-08 14:37 UTC, dbnicholson commented
/ok-to-test

2023-02-08 16:05 UTC, dbnicholson requested changes

2023-02-08 16:05 UTC, dbnicholson commented on src/libostree/ostree-async-progress.h
> +typedef void (*OstreeAsyncProgressChanged) (OstreeAsyncProgress *self, gpointer user_data);
Also, I think this should be used in the above definition of `OstreeAsyncProgressClass` for consistency.

2023-02-09 10:53 UTC, tintou commented
Actually when looking at it, this can't give good results with the introspection as the callback can be called multiple times after that this function has been called so it can't be correctly introspected. It is better to mark is as not introspectable to avoid using it and getting unexpected results.

2023-02-09 13:22 UTC, tintou commented
The introspection has only [4 types of scopes](https://gi.readthedocs.io/en/latest/annotations/giannotations.html#type-signature):
 * `call` (default) - Only valid for the duration of the call. Can be called multiple times during the call.
 * `async` - Only valid for the duration of the first callback invocation. Can only be called once.
 * `notified` - valid until the GDestroyNotify argument is called. Can be called multiple times before the GDestroyNotify is called.
 * `forever` - valid until the process terminates.

Here it would have been `notified` but there is no way to be notified when the signal will be disconnected so if the introspection has to allocate memory that is passed to the `user_data` it has to way to know when to free it.

2023-03-17 15:31 UTC, cgwalters approved these changes

2023-03-17 15:31 UTC, cgwalters approved these changes

2023-03-17 15:32 UTC, merged