ostree-sysroot-deploy: check if deployments are in the same stateroot.
ostreedev/ostree pull request #3234
Opened 2024-04-30 15:52 UTC by jmarrero

Our code currently does not check for stateroot as a differentiator between deployments, however given that we allow multiple stateroots, we should see them as different deployments in the same way we check for kargs for example.

2024-05-01 09:47 UTC, ericcurtin approved these changes
I agree with this, but I am curious what is the use case where all the previous checks have not returned FALSE already. The case where this happens in real-life. We can't depend on changing kargs this is correct, we use ostree=true in our Android Bootloader images for example.

2024-05-01 12:56 UTC, jmarrero commented
thanks for the review!
Single Node Openshift uses stateroots for managing faster upgrades. And they hit this.

See OCPBUGS-30276

just trying to confirm locally this works as intended before moving this out of draft.

2024-05-01 14:44 UTC, cgwalters requested changes
Ooh, good catch.  Fun bug.  I am actually looking forward to us trying to reuse the stateroot stuff more broadly as it's a very powerful thing.

I think it'd be relatively straightforward to do a test case for this in tests/admin-test.sh or so, I can help with that

2024-05-01 14:44 UTC, cgwalters commented on src/libostree/ostree-sysroot-deploy.c
> +  g_autofree char *a_stateroot = ostree_deployment_get_osname (a);
These should both just be `const char *`

2024-05-02 00:09 UTC, jmarrero commented
I can see the failure reported in the original issue with the test when I remove my changes:

```
error: Reloading deployments after commit: loading sysroot: Parsing deployment /ostree/boot.0/testos2/7bd091ad6955c0e7ef41bab65adb016275664b55efc0d10a0c8cb263da3c1e4e/0 in stateroot 'testos2': readlinkat: No such file or directory
```

2024-05-02 00:19 UTC, cgwalters approved these changes

2024-05-02 00:38 UTC, cgwalters commented
> [2024-05-02T00:14:50.093Z] FAIL: tests/test-libarchive-import 11 /libarchive/selinux - OSTree:ERROR:tests/test-libarchive-import.c:681:test_libarchive_selinux: assertion failed (error == NULL): Child process exited with code 1 (g-spawn-exit-error-quark, 1)


Hmm that one is weird.

2024-05-03 19:06 UTC, cgwalters commented
@jmarrero I think this just needs a rebase :surfer:

2024-05-04 01:34 UTC, merged