libostree/deploy: create composefs image even if `maybe`
ostreedev/ostree pull request #3353
Opened 2024-12-11 21:56 UTC by jlebon

Currently, we only create a composefs image if the enablement level is `true`. But ISTM there's no reason we shouldn't lower the threshold to `maybe` instead.

This makes it slightly less awkward to ratchet in composefs. Without this, it's hard to have new nodes use composefs while still allowing old nodes with ancient libostree to upgrade to the same image (without composefs).

2024-12-11 21:56 UTC, jlebon commented
Haven't tested this yet.

2024-12-12 01:34 UTC, jlebon commented
OK so after looking at this a bit more, this doesn't quite do what I thought. I was planning to use `enabled = maybe` in the config file, but `maybe` is already the default value if it's missing. So this has a much larger impact; i.e. all libostree clients with composefs compiled in and no config specified would now start creating and mounting composefs images. Which... maybe it has baked enough now? But we'd need to raise awareness.

If we don't think we're ready for that, then we might need another config knob to express what we want here.

2024-12-12 21:22 UTC, cgwalters commented
>  If you're compiling libostree today with composefs enabled, then you're already tracking this tech and possibly using it already. 

Maybe. I think it's probably fine to do that change and release note it heavily, but it *is* a semantic change.

>Without this, it's hard to have new nodes use composefs while still allowing old nodes with ancient libostree to upgrade to the same image (without composefs).

That said, how does patching the *current* ostree help at all for this problem? Unless we back port this patch to y-stream branches...but I dunno, that seems like a big task to do.

I think we need to investigate instead fixing this up post-deploy pre-reboot via code execution which we're already tracking in other venues (e.g. the discussions of using `podman run <target image> bootc install`) which already give us a way to ensure we're running the *new* OS image.

2024-12-12 21:22 UTC, cgwalters requested changes
Marking as requested changes just to signal it's reviewed

2024-12-12 21:23 UTC, cgwalters commented
If we were to try to cherry pick this patch to older releases, it'd definitely also want https://github.com/ostreedev/ostree/pull/3326/commits/a6d07b6cc3a6030307c6e29aaf33944ff0ad8c8b for example

2024-12-13 01:23 UTC, jlebon commented
> > If you're compiling libostree today with composefs enabled, then you're already tracking this tech and possibly using it already.
> 
> Maybe. I think it's probably fine to do that change and release note it heavily, but it _is_ a semantic change.

OK cool, I'll test it in earnest. Definitely at least some tests need to be adjusted it seems.

> > Without this, it's hard to have new nodes use composefs while still allowing old nodes with ancient libostree to upgrade to the same image (without composefs).
> 
> That said, how does patching the _current_ ostree help at all for this problem? Unless we back port this patch to y-stream branches...but I dunno, that seems like a big task to do.

Backporting is not necessary.

With this patch, the node eventually converges to composefs enabled. The first upgrade to an image which has this patch will not have composefs. The second upgrade starting from this patch and onward will.

> I think we need to investigate instead fixing this up post-deploy pre-reboot via code execution

For the OCP/OKD case, we clearly need to eventually be able to just assume that composefs is on to unblock other feature work that rely on it. There's indeed workarounds we could do (though actually with this patch, one workaround is just redeploy the same commit after updating) though we're also close I think to be able to addressing the old bootimages problem which would just solve... so much. At least until then, we can get the hardening benefits of composefs.

2024-12-13 10:29 UTC, travier commented
> With this patch, the node eventually converges to composefs enabled. The first upgrade to an image which has this patch will not have composefs. The second upgrade starting from this patch and onward will.

If I understand correctly, this means that we do not explicitly enable composefs on RHCOS yet but any system that updates using an ostree with this code will start using composefs?

2024-12-13 10:31 UTC, travier commented
Hum, I'm just realizing that we might need this for the Atomic Desktops as well and now I don't understand how we could make it work in Fedora CoreOS anymore without this 😕

2024-12-13 15:54 UTC, cgwalters commented
The more I think about this the more I lean towards trying to cleanly split "generate" vs "consume".


Today `composefs = maybe` is not really different from `composefs = no` right? So maybe the cleanest is the default for composefs is set to `no` in the code, but if composefs is compiled in we default to generating a composefs unconditionally.

2024-12-13 16:29 UTC, jlebon commented
> If I understand correctly, this means that we do not explicitly enable composefs on RHCOS yet but any system that updates using an ostree with this code will start using composefs?

Yeah, exactly. RHCOS would ship with `enabled = maybe` for now.

> Hum, I'm just realizing that we might need this for the Atomic Desktops as well and now I don't understand anymore how we could make it work in Fedora CoreOS without this 😕

It worked in FCOS because the previous version has new enough libostree. FCOS has periodic barriers. Upgrade tests would've hit this if it weren't covered by one of the existing barriers. It _should_ equally work in the Atomic Desktops given that we require that nodes go through every major at least once.

> So maybe the cleanest is the default for composefs is set to `no` in the code, but if composefs is compiled in we default to generating a composefs unconditionally.

I'm OK with that. If we do that, then we should also make the deploy logic match the `ostree-prepare-root` logic where we always parse the config and correctly error out if composefs is not compiled in but is enforced.

2024-12-13 16:39 UTC, jlebon commented
> If we do that, then we should also make the deploy logic match the `ostree-prepare-root` logic where we always parse the config and correctly error out if composefs is not compiled in but is enforced.

Hmm, based on https://github.com/ostreedev/ostree/blob/7daeaa2311abb813003151f4abcb2e02cf8f0315/src/libostree/ostree-sysroot-deploy.c#L657-L658 I think that was an unintended gap in the current code. Will fix!

2024-12-13 16:50 UTC, jlebon commented
Updated!

2024-12-13 18:03 UTC, cgwalters commented
But won't this cause the opposite problem where we will just bomb out on upgrades because the new prepare-root won't find a composefs for systems that didn't have it configured on previously?

2024-12-13 18:32 UTC, jlebon commented
> But won't this cause the opposite problem where we will just bomb out on upgrades because the new prepare-root won't find a composefs for systems that didn't have it configured on previously?

I think you're right.

So... I think we either have to leave the default on `maybe` (but still change the deploy threshold down to `maybe`), or add a new knob to control the deploy and ostree-prepare-root behaviours separately?

2024-12-13 18:34 UTC, cgwalters commented
Wouldn't https://github.com/ostreedev/ostree/pull/3353?new_mergebox=true#issuecomment-2541751214 work?

2024-12-13 19:01 UTC, jlebon commented
> Wouldn't [my previous suggestion](https://github.com/ostreedev/ostree/pull/3353?new_mergebox=true#issuecomment-2541751214) work?

Gotcha, I had misunderstood your suggestion.

Hmm... it's confusing though that we'd still be generating composefs images even if it's been explicitly turned off. I feel like this is quite close to the `maybe` suggestion, but goes one step further than it needs to and lowers the creation threshold to `no`?

Another way to look at the `maybe` approach I think is that it makes the deploy and mount logic consistent. The mount logic is "if the composefs image is available, then mount it" and the deploy logic becomes "if composefs is available, then generate it". This is also closer to the usual semantic of `maybe`.

2024-12-17 15:25 UTC, cgwalters commented on src/libotcore/otcore-prepare-root.c
> +#define COMPOSEFS_TRISTATE_DEFAULT_VALUE OT_TRISTATE_YES
This still needs to change back to `OT_TRISTATE_MAYBE` right?

2024-12-17 18:38 UTC, jlebon commented
Updated this now but haven't tested it yet!

2024-12-17 19:02 UTC, jlebon commented
OK yup, can confirm this allows ratcheting from older libostree versions. :heavy_check_mark:

```
$ cosa run --qemu-image /srv/imgs/rhcos-412.86.202412161907-0-qemu.x86_64.qcow2
[root@cosa-devsh ~]# rpm-ostree rebase --experimental ostree-unverified-image:oci-archive:$(ls /mnt/workdir/builds/latest/x86_64/*.ociarchive)
[root@cosa-devsh ~]# ls -la /ostree/deploy/rhcos/deploy/*/.*.cfs
ls: cannot access '/ostree/deploy/rhcos/deploy/*/.*.cfs': No such file or directory
[root@cosa-devsh ~]# reboot
[root@cosa-devsh ~]# rpm-ostree status -v
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree-unverified-image:oci-archive:/mnt/workdir/builds/latest/x86_64/scos-9.202412171851-0-ostree.x86_64.ociarchive (index: 0)
                   Digest: sha256:24eef5695d7c95bf07219093c8f6183596fe3b4144af38d673b8ebc7fe88ec2e
                  Version: 9.202412171851-0 (2024-12-17T18:55:00Z)
                   Commit: 35341846a7951dd16124f50a068c4e0d5cfc47d854fbc8ad7efedeb93c8867c9
                   Staged: no
                StateRoot: rhcos

  a99301b69bcdc27b5dba71aa103fdfd896e6ceb1345db9a108a4ee90b113bcd2 (index: 1)
                  Version: 412.86.202412161907-0 (2024-12-16T19:11:04Z)
                   Commit: a99301b69bcdc27b5dba71aa103fdfd896e6ceb1345db9a108a4ee90b113bcd2
                           ├─ rhel-8.6-appstream (2024-12-16T18:35:25Z)
                           ├─ rhel-8.6-baseos (2024-12-11T00:13:42Z)
                           ├─ rhel-8.6-fast-datapath (2024-12-10T00:08:42Z)
                           └─ rhel-8.6-server-ose-4.12 (2024-12-16T19:04:04Z)
                StateRoot: rhcos
[root@cosa-devsh ~]# rpm-ostree rebase :35341846a7951dd16124f50a068c4e0d5cfc47d854fbc8ad7efedeb93c8867c9
[root@cosa-devsh ~]# ls -la /ostree/deploy/rhcos/deploy/*/.*.cfs                                                                                                                                                                                                                                                            
-rw-r--r--. 1 root root 5849088 Dec 17 18:56 /ostree/deploy/rhcos/deploy/35341846a7951dd16124f50a068c4e0d5cfc47d854fbc8ad7efedeb93c8867c9.1/.ostree.cfs
[root@cosa-devsh ~]# reboot
[core@cosa-devsh ~]$ findmnt /
TARGET SOURCE    FSTYPE  OPTIONS
/      composefs overlay ro,relatime,seclabel,lowerdir=/run/ostree/.private/cfsroot-lower::/sysroot/ostree/repo/objects,redirect_dir=on,metacopy=on
```

2024-12-17 19:20 UTC, cgwalters approved these changes

2024-12-17 20:34 UTC, cgwalters commented
/override ci/prow/fcos-e2e

2024-12-17 20:34 UTC, merged

2025-01-09 15:37 UTC, travier commented
This will likely impact Fedora IoT & RHEL 4 Edge as well cc @pcdubs

2025-01-09 15:40 UTC, cgwalters commented
In conversations here we should start trying to use terms like "generated" vs "runtime enabled" instead of just "enabled" - a root problem here is we're conflating those two things with the single flag right now.

Hmmm...you're trying to avoid having composefs runtime-enabled for stable releases just because ostree updated? That makes sense if so.

The simplest thing that comes to mind here is we can just unconditionally always generate the composefs blob, even if `composefs = no`. It doesn't have a large cost.

Then the flag becomes purely about runtime state, which is far easier to reason about.

2025-01-09 15:47 UTC, travier commented
> In conversations here we should start trying to use terms like "generated" vs "runtime enabled" instead of just "enabled" - a root problem here is we're conflating those two things with the single flag right now.

👍🏻

> Hmmm...you're trying to avoid having composefs runtime-enabled for stable releases just because ostree updated? That makes sense if so.

Yes

> The simplest thing that comes to mind here is we can just unconditionally always generate the composefs blob, even if `composefs = no`. It doesn't have a large cost.
> 
> Then the flag becomes purely about runtime state, which is far easier to reason about.

Sounds good to me.

> EDIT: If we go that route though, it would mean that people who _don't_ set the composefs configuration would actually switch to be enabled. I think that's probably fine per discussion previously; people who don't want composefs at all for custom OSes can already compile it out, and they can also set the runtime config.

👍🏻

2025-01-09 16:01 UTC, cgwalters commented
:arrow_right: https://github.com/ostreedev/ostree/pull/3366

2025-01-09 16:09 UTC, cgwalters commented
In the intermediate time though, I think we should *also* start telling everyone who doesn't want composefs to explicitly disable it in their base images.

Obviously the goal of https://github.com/ostreedev/ostree/pull/3366 is to be compatible, and I think we'll do that, but maybe at some point in the future we do push for it to be on by default.