[RFC] prepare-root: Add composefs.enabled=verity
ostreedev/ostree pull request #3354
Opened 2024-12-16 12:02 UTC by ruihe774

In the current implementation, a composefs deploy is either:
- signed by key and verified by fs-verity, or
- not signed and not verified.

This PR adds a new supported value `verity` to `composefs.enabled`, which:
- requires the composefs to be verified by fs-verity;
- does not require it to be signed.

The idea is that:
- If we do not specify `LCFS_MOUNT_FLAGS_REQUIRE_VERITY` (the underlying of which is `verity=require` when mounting overlayfs), overlayfs does not verify file data even if fs-verity digests are present in the image.
- It is difficult and troublesome to have the ostree commit signed in some circumstances. For example, when deploying with custom layering.
- In some cases, the integrity of the composefs image is already protected by other mechanisms, for example EVM. It is not necessary to verify the image by a key, but it is still necessary to verify file data referenced by the image using fs-verity to protect the integrity from disk corruption.

2024-12-16 16:16 UTC, cgwalters requested changes
ACK to the overall idea though the way I'd describe this is more "external signing". One thing I could imagine doing here is checking if a stamp file like `/run/ostree/composefs-signed` or so is present, then we skip our own signature checks and assume that an external systemd unit that ran before this code executed.

2024-12-16 16:16 UTC, cgwalters commented on src/switchroot/ostree-prepare-root.c
> +          if (composefs_config->require_verity)
I'm confused by this change which is underneath `if is_signed` which always implies `require_verity` right? 

I think I'd just add a `g_assert (composefs_config->require_verity)` here instead or so.

2024-12-16 16:33 UTC, cgwalters reviewed
Thanks, looks sane. Can you also update `man/ostree-prepare-root.xml`?

2024-12-16 16:34 UTC, ruihe774 commented
> One thing I could imagine doing here is checking if a stamp file like /run/ostree/composefs-signed or so is present, then we skip our own signature checks and assume that an external systemd unit that ran before this code executed.

I think it's a bit of complicated and over-designed. If we do that, the "external" verification tool needs to explicitly cooperate with ostree and write the stamp file, or the end user needs to write a custom systemd service and add it to initramfs, which is troublesome.

2024-12-16 16:51 UTC, ruihe774 commented
> Can you also update `man/ostree-prepare-root.xml`?

Done. PTAL.

2024-12-16 19:01 UTC, cgwalters approved these changes
Looks good!

Our CI just fell over, I filed https://github.com/ostreedev/ostree/pull/3356 to get some things fixed and I think we need to have that resolved before merging more things. But I'll get this in after that, thanks again!

2024-12-17 18:08 UTC, cgwalters commented
/ok-to-test

2024-12-17 19:59 UTC, merged

2025-01-20 19:31 UTC, champtar commented
To help with upgrades, would a `verity-maybe` make sense ?

2025-01-21 18:50 UTC, ruihe774 commented
> To help with upgrades, would a `verity-maybe` make sense ?

You mean setting option `verity=on` on the overlayfs mount? Unfortunately, libcompose does not support it.

It only supports either no option (equivalent to `verity=off`) or `verity=require`.

https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html#fs-verity-support
https://github.com/containers/composefs/blob/2e98bef7a783a850b431273fd6928c1d5ff280f8/libcomposefs/lcfs-mount.h#L25

BTW, `LCFS_MOUNT_FLAGS_TRY_VERITY` is to try whether the kernel support the `verity` mount option, not to try whether fs-verity is enabled.

To upgrade, you can simply enable fs-verity for all files under `repo/objects` (There are existing tools to do that) before you deploy with `composefs.enabled=verity`.

2025-04-01 14:28 UTC, allisonkarlitskaya commented
I'm late to the party here but is it too late to change the option?  Before this change, afaik, all options were boolean and the config file was effectively toml.  This takes us into a somewhat more freeform direction.... probably ini-ish.... that might make things more difficult in the future if we want to add more advanced features.

Something more like

```toml
[composefs]
enable=true
verity=true
```

instead?

2025-04-01 15:29 UTC, cgwalters commented
> This takes us into a somewhat more freeform direction.... probably ini-ish

It's always been ini, we've parsed using GKeyFile; and especially booleans in ini/GKeyFile accept values like "yes/no" and "0/1" that aren't valid in TOML. 

You're right of course regardless that it'd definitely have been cleaner to use a separate boolean for `verity=true`. (That said, `verity=true` should probably imply `enable=true` just to simplify things further) Happy to do that now too.

I'm assuming you're asking this because you want to reimplement it in composefs-rs, but note there is already Rust code in bootc that's parsing this too, and I did have to adjust it for this in e.g. https://github.com/bootc-dev/bootc/commit/06933ed3a2b069bad1f9a002452e2e025a48c0ba